serverAddr = "frp.freefrp.net"
serverPort = 5443

user = u1
auth.method = "token"
auth.token = "jknxsxHBFp1KLW39"


[[proxies]]
name = "web1_xxxxx"
type = "http"
localIP = "127.0.0.1"
localPort = 5000
customDomains = ["nas.yourdomain.com"]
transport.useEncryption = true  
transport.useCompression = true 

[[proxies]]
name = "web2_xxxxx"
type = "https"
localIP = "127.0.0.1"
localPort = 5001
customDomains = ["nas.yourdomain.com"]
transport.useEncryption = true 
transport.useCompression = true 

[[proxies]]
name = "tcp1_xxxxx"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 22222
transport.useEncryption = true  
transport.useCompression = true   
